version: "3.0"
services:
  qstars:
    build: .
    depends_on: 
      - db
    ports: 
     - "8000:8000"
    environment:
      - HTTP_HOST=0.0.0.0
      - SERVER_HOSTNAME=localhost
      
  db: 
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    