version: "3.0"
services:
  qstars:
    build: .
    depends_on: 
      - db
    ports: 
     - "8000:8000"
    environment:
      - HTTP_HOST=0.0.0.0
      - SERVER_HOSTNAME=localhost
    env_file:
      - example.env
      
  db: 
    image: "postgres:12-alpine"
    env_file:
      - example.env
    expose:
      - "5432"

  update-local-db:
    container_name: update_local_db
    image: "qstars:latest"
    restart: always
    build: .
    env_file:
      - example.env
    entrypoint:  bash /app/utility/db_init.sh
    depends_on:
      - db
  
  ci:
    container_name: qstars-ci
    image: "qstars:latest"
    build: .
    ports:
      - "8000:8000"
    env_file:
      - example.env
    entrypoint: /app/utility/run_tests.sh
    depends_on:
      - db